TWEET_QUEUE = "tweets"
IMAGE_QUEUE = "images"
DAILY_NUMBER_OF_TWEET_GENERATIONS = 1
DAILY_NUMBER_OF_IMAGE_GENERATIONS = 5
DAILY_NUMBER_OF_TEXT_TWEETS = 8
DAILY_NUMBER_OF_IMAGE_TWEETS = 2
MAX_TEXT_GENERETIONS_PER_REQUEST = 5
