# Generated by Django 3.1.7 on 2021-03-30 20:48

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenURI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('address', models.CharField(default=None, max_length=255, verbose_name='Wallet Address')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Description')),
                ('imageURL', models.URLField(blank=True, default=None, null=True, verbose_name='Image URL')),
                ('traits', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), default=list, size=None, verbose_name='Traits')),
            ],
        ),
    ]
