# Generated by Django 3.1.7 on 2021-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenuri',
            name='address',
            field=models.CharField(default=None, max_length=255, verbose_name='Wallet Address'),
        ),
    ]
